name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build PHP
      run: docker buildx build -f Dockerfile.php -t ghcr.io/${{ github.actor }}/cro-php-example:php .

    - name: Build Nginx
      run: docker buildx build -f Dockerfile.nginx -t ghcr.io/${{ github.actor }}/cro-php-example:nginx .

    - name: Push PHP
      run: docker push ghcr.io/${{ github.actor }}/cro-php-example:php

    - name: Push Nginx
      run: docker push ghcr.io/${{ github.actor }}/cro-php-example:nginx
